name: test_ubuntu_dockerhub_TinyTeX_learn_algorithm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install TeX Live
      run:  bash .github/workflows/install-texlive.sh
    - name: Test thesis
      run: |
        export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
        xelatex -interaction nonstopmode main.tex
