name: test_ubuntu_dockerhub_TinyTeX_learn_algorithm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull docker image
      run: |
        docker pull dustincys/tinytex-hithesis:latest

    - name: Test algorithm book
      run: |
        CURRENTDIR=$(pwd)
        docker run --rm -i -v $(pwd):/home/runner dustincys/tinytex-hithesis:latest xelatex -interaction nonstopmode main.tex
        cd $CURRENTDIR
      
