name: test_ubuntu_dockerhub_TinyTeX_learn_algorithm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull docker image
      run: |
        docker pull xiaoqiangwu/ubuntu-texlive:v2.0
    - name: Test doc
      run: |
        docker run --rm -i -v $(pwd):/home/runner xiaoqiangwu/ubuntu-texlive:v2.0 xelatex -interaction nonstopmode main.tex

    # steps:
    # - uses: actions/checkout@v2
    # - name: Install TeX Live
    #   run:  bash .github/workflows/install-texlive.sh
    # - name: Test thesis
    #   run: |
    #     export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
    #     xelatex -interaction nonstopmode main.tex
